#!/bin/bash -ex

# This can for sure to be done much better, but let's hope it works.

DOCKER_ARCH=${BUILD_ARCH:-amd64}
DOCKER_ORG=samip537
DOCKER_IMAGE=docker-flextv:${DOCKER_ARCH}

if [ ${BUILD_ARCH} = "amd64" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
                -t $DOCKER_ORG/$DOCKER_IMAGE \
                -f Dockerfile .
fi

if [ ${BUILD_ARCH} = "arm32v6" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
                -t $DOCKER_ORG/$DOCKER_IMAGE \
                -f Dockerfile.armhf .
fi

if [ ${BUILD_ARCH} = "arm32v7" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
                -t $DOCKER_ORG/$DOCKER_IMAGE \
                -f Dockerfile.armhf .
fi

if [ ${BUILD_ARCH} = "arm64v8" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
                -t $DOCKER_ORG/$DOCKER_IMAGE \
                -f Dockerfile.aarch64 .
fi
